// Editable placeholder menu data. Replace names, descriptions, prices, and availability with the live Panino's Toast menu before launch.
export type MenuItem = { name: string; description: string; price: string; popular?: boolean };
export type MenuCategory = { slug: string; name: string; intro: string; items: MenuItem[] };
export const menuCategories: MenuCategory[] = [
 {slug:'pizza',name:'Pizza',intro:'Classic New York-style pies with a crisp foldable crust.',items:[{name:'18” Cheese Pizza',description:'Tomato sauce, whole milk mozzarella, oregano.',price:'$18.95',popular:true},{name:'14” Cheese Pizza',description:'Smaller classic pie for sharing.',price:'$14.95'},{name:'Sicilian Square',description:'Thick pan crust, tomato, mozzarella, basil.',price:'$24.95'}]},
 {slug:'slices',name:'Pizza by the Slice',intro:'Fast downtown slices for lunch, pre-game, and late-night.',items:[{name:'Cheese Slice',description:'Oversized New York-style slice.',price:'$3.95',popular:true},{name:'Pepperoni Slice',description:'Crisp pepperoni, mozzarella, tomato sauce.',price:'$4.75'},{name:'Daily Specialty Slice',description:'Rotating chef selection.',price:'$5.50'}]},
 {slug:'specialty-pizzas',name:'Specialty Pizzas',intro:'House combinations built for big flavor.',items:[{name:'Downtown Supreme',description:'Pepperoni, sausage, peppers, onions, mushrooms, olives.',price:'$27.95',popular:true},{name:'Margherita',description:'Fresh mozzarella, tomato, basil, olive oil.',price:'$25.95'},{name:'Meatball Ricotta',description:'Sliced meatballs, ricotta dollops, mozzarella.',price:'$28.95'}]},
 {slug:'strombolis',name:'Strombolis',intro:'Rolled dough baked golden with marinara on the side.',items:[{name:'Pepperoni Stromboli',description:'Pepperoni, mozzarella, parmesan.',price:'$11.95'},{name:'Italian Stromboli',description:'Ham, salami, pepperoni, provolone.',price:'$12.95'}]},
 {slug:'calzones',name:'Calzones',intro:'Stuffed with ricotta and mozzarella.',items:[{name:'Cheese Calzone',description:'Ricotta, mozzarella, parmesan.',price:'$10.95'},{name:'Spinach Calzone',description:'Spinach, garlic, ricotta, mozzarella.',price:'$11.95'}]},
 {slug:'wings',name:'Wings',intro:'Crispy wings with classic sauces.',items:[{name:'Buffalo Wings',description:'Hot, medium, mild, or garlic parmesan.',price:'10 for $14.95',popular:true},{name:'BBQ Wings',description:'Sweet smoky barbecue sauce.',price:'10 for $14.95'}]},
 {slug:'pasta',name:'Pasta',intro:'Italian-American favorites served with garlic knots.',items:[{name:'Spaghetti & Meatballs',description:'Marinara, house meatballs, parmesan.',price:'$15.95',popular:true},{name:'Chicken Parm Pasta',description:'Breaded chicken, marinara, mozzarella.',price:'$17.95'},{name:'Fettuccine Alfredo',description:'Creamy parmesan Alfredo sauce.',price:'$15.95'}]},
 {slug:'salads',name:'Salads',intro:'Fresh greens for lighter lunches.',items:[{name:'Classic Caesar',description:'Romaine, parmesan, croutons.',price:'$9.95'},{name:'Antipasto Salad',description:'Italian meats, provolone, olives, peppers.',price:'$13.95'}]},
 {slug:'hot-subs',name:'Hot Subs',intro:'Toasted Italian-American heroes.',items:[{name:'Chicken Parm Sub',description:'Crispy chicken, marinara, mozzarella.',price:'$11.95',popular:true},{name:'Meatball Parm Sub',description:'House meatballs, marinara, melted cheese.',price:'$10.95'}]},
 {slug:'cold-subs',name:'Cold Subs',intro:'Deli-style subs made to order.',items:[{name:'Italian Combo',description:'Ham, salami, capicola, provolone, lettuce, tomato.',price:'$11.95'},{name:'Turkey Provolone',description:'Turkey, provolone, lettuce, tomato, oil and vinegar.',price:'$10.95'}]},
 {slug:'desserts',name:'Desserts',intro:'Sweet finishes after pizza and pasta.',items:[{name:'Cannoli',description:'Crisp shell, sweet ricotta filling.',price:'$4.95'},{name:'Tiramisu Cup',description:'Espresso-soaked ladyfingers, mascarpone.',price:'$6.95'}]},
 {slug:'gelato',name:'Gelato',intro:'Creamy Italian-style gelato.',items:[{name:'Pistachio Gelato',description:'Rich pistachio flavor.',price:'$5.95'},{name:'Chocolate Gelato',description:'Dense, smooth chocolate.',price:'$5.95'}]},
 {slug:'drinks',name:'Drinks',intro:'Fountain drinks, bottled beverages, and espresso.',items:[{name:'Fountain Drink',description:'Coke products.',price:'$2.95'},{name:'San Pellegrino',description:'Sparkling Italian soda.',price:'$3.95'}]},
 {slug:'lunch-specials',name:'Lunch Specials',intro:'Weekday value for downtown offices, students, and quick meetings.',items:[{name:'Two Slices & Drink',description:'Cheese or pepperoni slices with a fountain drink.',price:'$8.95',popular:true},{name:'Half Sub + Side Salad',description:'Select subs with a crisp house salad.',price:'$10.95'},{name:'Pasta Lunch Bowl',description:'Smaller pasta portion with garlic knot.',price:'$11.95'}]},
];
